language: node_js
node_js:
  - 14
script:
  # - yarn lint
  - yarn test:ci
after_success:
  - npx codecov

deploy:
  provider: script
  edge: true
  script: yarn install && yarn run deploy
  skip_cleanup: true
  on:
    branch: master